### ISSUE TITLE
ArrayIndexOutOfBoundsException when using SINGLE_TABLE and ConnectedStatementsWriter

### ISSUE THREAD

**Issue by liefke** [liefke/org.fastnate#38]
Writing two entities of two different subclasses in the same class hierarchy with default inheritance type `SINGLE_TABLE` results in an `ArrayIndexOutOfBoundsException`:

    java.lang.ArrayIndexOutOfBoundsException: 6
        at org.fastnate.generator.statements.ConnectedStatementsWriter$PreparedInsertStatement.setColumnValue(ConnectedStatementsWriter.java:113)
        at org.fastnate.generator.context.PrimitiveProperty.addInsertExpression(PrimitiveProperty.java:235)
        at org.fastnate.generator.EntitySqlGenerator.writeInserts(EntitySqlGenerator.java:268)
        at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:194)
        at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:168)
        ...

**Comment by liefke** [comment]
Fixed
