### ISSUE TITLE
DiscriminatorColumn+ DiscriminatorValue: A value for B_TYP was assigned twice

### ISSUE THREAD

**Issue by schowave** [liefke/org.fastnate#59]
The entity structure, looks like this:

_@MappedSuperclass_
public **abstract class AbstractA** {

  _@Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "ID")_
  protected Long id;
}

_@MappedSuperclass_
public **abstract class AbstractB** extends AbstractA {
  
  _@Column(name = "B_TYP")_
  protected String typ;

  public String getTyp() {
    return typ;
  }

  public void setTyp(String typ) {
    this.typ = typ;
  }
}

_@Entity
@Access(AccessType.FIELD)
@Table(name = "TABLE")
@Cacheable(false)
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(
    name = "B_TYP",
    discriminatorType = DiscriminatorType.STRING,
    length = 20)_
public abstract **class AbstractC** extends AbstractB {
}

_@Entity
@Access(AccessType.FIELD)
@Table(name = "CONCRETE")
@Cacheable(false)
@DiscriminatorValue("CONCRETE_TYP")_
public **class Concrete** extends AbstractC {

  _@Column_
  private String col;

  public String getCol() {
    return tabellenart;
  }

  public void setCol(String col) {
    this.col= col;
  }
}

When I run the fastnate EntityImporter like this:

`var properties = new Properties();`
`properties.put(OUTPUT_FILE_KEY, "src/main/resources/data.sql");`
`var entityImporter = new EntityImporter(properties);`
`entityImporter.addDataProvider(new ConcreteDataProvider());`
`entityImporter.importData();`

Some Insert Statements are generated for the other tables, but with the first element from Concrete class, it fails with an IllegalArgumentException:

`A value for B_TYP was assigned twice
java.lang.IllegalArgumentException: A value for B_TYP was assigned twice
	at org.fastnate.generator.statements.AbstractStatementsWriter$AbstractTableStatement.setColumnValue(AbstractStatementsWriter.java:75)
	at org.fastnate.generator.context.PrimitiveProperty.addInsertExpression(PrimitiveProperty.java:130)
	at org.fastnate.generator.EntitySqlGenerator.writeInserts(EntitySqlGenerator.java:265)
	at org.fastnate.generator.EntitySqlGenerator.writeInserts(EntitySqlGenerator.java:243)
	at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:191)
	at org.fastnate.generator.EntitySqlGenerator.writeInserts(EntitySqlGenerator.java:279)
	at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:191)
	at org.fastnate.generator.EntitySqlGenerator.writeInserts(EntitySqlGenerator.java:279)
	at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:191)
	at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:165)
	at org.fastnate.generator.EntitySqlGenerator.write(EntitySqlGenerator.java:207)
	at org.fastnate.data.AbstractDataProvider.writeEntities(AbstractDataProvider.java:42)
	at org.fastnate.data.EntityImporter.importData(EntityImporter.java:389)
	at org.fastnate.data.EntityImporter.importData(EntityImporter.java:328)`

I deleted the Annotation @DiscriminatorColumn in the **AbstractC** class and afterwards the generation worked. But this annotation is needed for my JPA Entities. Am I doing something wrong here, or is it an issues with fastnate?

**Comment by schowave** [comment]
Update: I solved this issue, by deleting the field "typ" from class AbstractB. 
This field is actually not needed, because the class Concrete can implement a getter for the type, which is in my case an enum.

So actually Fastnate is correcting my code here, +1

**Comment by liefke** [comment]
I just tried your approach with Hibernate and it is complaining, too (as expected):
```
org.hibernate.MappingException: Repeated column in mapping for entity: Concrete column: type (should be mapped with insert="false" update="false")
	at org.hibernate.mapping.PersistentClass.checkColumnDuplication(PersistentClass.java:764)
```

So works as designed ;-)
